GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
  "content": "REST client is good in testing backend",
  "important": true
}

###

GET https://render-test-do6i.onrender.com/api/notes/

###

POST https://render-test-do6i.onrender.com/api/notes HTTP/1.1
content-type: application/json

{
  "content": "REST client is good in testing backend",
  "important": true
}